-- =====================================================================
-- Respaldo del esquema de la base de datos — plataforma-iot-tesis
-- =====================================================================
-- Este archivo NO contiene datos (usuarios, dispositivos, telemetría) —
-- solo la estructura: tablas, relaciones, políticas de seguridad (RLS)
-- y las funciones/trigger que provisionan un tenant nuevo al registrarse
-- un usuario.
--
-- Generado a mano a partir de consultas a information_schema / pg_catalog
-- en el SQL Editor de Supabase (no vía `supabase db dump`, que requiere
-- Docker). Refleja el estado del esquema en la fecha de este commit.
--
-- Para reconstruir el proyecto desde cero en un Supabase nuevo:
--   1. Correr este archivo completo en el SQL Editor.
--   2. Configurar Authentication > Providers según corresponda.
--   3. Volver a apuntar HIVEMQ_* / SUPABASE_* en los .env del bridge y
--      del frontend al nuevo proyecto.
-- =====================================================================

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------
-- Funciones (van primero: `devices.tenant_id` usa get_my_tenant_id()
-- como default, así que la función debe existir antes de crear la tabla)
-- ---------------------------------------------------------------------

-- Devuelve el tenant_id del usuario autenticado actual. Se usa dentro
-- de las políticas RLS y como default de tenant_id en `devices`.
create or replace function public.get_my_tenant_id()
 returns uuid
 language sql
 stable security definer
as $function$
  select tenant_id from profiles where id = auth.uid();
$function$;

-- Se ejecuta automáticamente (vía el trigger de más abajo) cada vez que
-- alguien se registra: crea su tenant y su perfil como admin de ese
-- tenant. Es lo que hace que cada usuario nuevo "funde" su propia
-- organización sin lógica de tenant hardcodeada en el código de la app.
create or replace function public.handle_new_user()
 returns trigger
 language plpgsql
 security definer
 set search_path to 'public'
as $function$
declare
  new_tenant_id uuid;
begin
  insert into tenants (name)
  values (coalesce(new.raw_user_meta_data->>'full_name', new.email) || ' - Organización')
  returning id into new_tenant_id;

  insert into profiles (id, tenant_id, full_name, role)
  values (new.id, new_tenant_id, new.raw_user_meta_data->>'full_name', 'admin');

  return new;
end;
$function$;

-- ---------------------------------------------------------------------
-- Tablas
-- ---------------------------------------------------------------------

-- Catálogo fijo de planes — define cuántos dispositivos puede tener un
-- tenant y cuántas lecturas puede recibir cada dispositivo. No son pagos
-- reales, es para demostrar el concepto de límites diferenciados por plan.
create table public.plans (
  id text not null,
  name text not null,
  max_devices int not null,
  max_readings_per_device int not null,
  constraint plans_pkey primary key (id)
);

insert into public.plans (id, name, max_devices, max_readings_per_device) values
  ('basico', 'Básico', 3, 10),
  ('medio', 'Medio', 5, 25),
  ('pro', 'Pro', 10, 50);

create table public.tenants (
  id uuid not null default gen_random_uuid(),
  name text not null,
  plan_id text not null default 'basico',
  plan_selected boolean not null default false,
  created_at timestamp with time zone default now(),
  constraint tenants_pkey primary key (id),
  constraint tenants_plan_id_fkey foreign key (plan_id) references public.plans (id)
);

create table public.profiles (
  id uuid not null,
  tenant_id uuid,
  full_name text,
  role text default 'member',
  created_at timestamp with time zone default now(),
  constraint profiles_pkey primary key (id),
  constraint profiles_id_fkey foreign key (id) references auth.users (id),
  constraint profiles_tenant_id_fkey foreign key (tenant_id) references public.tenants (id)
);

create table public.devices (
  id uuid not null default gen_random_uuid(),
  tenant_id uuid default get_my_tenant_id(),
  name text not null,
  device_key text not null,
  status text default 'offline',
  created_at timestamp with time zone default now(),
  metric_key text,
  unit text,
  constraint devices_pkey primary key (id),
  constraint devices_device_key_key unique (device_key),
  constraint devices_tenant_id_fkey foreign key (tenant_id) references public.tenants (id)
);

create table public.telemetry (
  id bigint generated by default as identity,
  tenant_id uuid,
  device_id uuid,
  payload jsonb not null,
  recorded_at timestamp with time zone default now(),
  constraint telemetry_pkey primary key (id),
  constraint telemetry_tenant_id_fkey foreign key (tenant_id) references public.tenants (id),
  constraint telemetry_device_id_fkey foreign key (device_id) references public.devices (id) on delete cascade
);

-- ---------------------------------------------------------------------
-- Trigger (vive en el esquema auth, se define aparte de las funciones)
-- ---------------------------------------------------------------------

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function handle_new_user();

-- ---------------------------------------------------------------------
-- Triggers de límites de plan
-- ---------------------------------------------------------------------

-- Bloquea crear un dispositivo si el tenant ya llegó al máximo de su plan.
create or replace function public.enforce_device_limit()
 returns trigger
 language plpgsql
 security definer
 set search_path to 'public'
as $function$
declare
  current_count int;
  max_allowed int;
begin
  select count(*) into current_count from devices where tenant_id = new.tenant_id;
  select p.max_devices into max_allowed
    from plans p join tenants t on t.plan_id = p.id where t.id = new.tenant_id;

  if current_count >= max_allowed then
    raise exception 'Límite de dispositivos alcanzado para tu plan (máx. %).', max_allowed;
  end if;

  return new;
end;
$function$;

create trigger before_insert_device_check_limit
  before insert on public.devices
  for each row execute function enforce_device_limit();

-- Bloquea guardar una lectura si ese dispositivo ya llegó al máximo de
-- lecturas DIARIAS permitido por el plan de su tenant. Es una ventana
-- móvil de 24h (recorded_at >= now() - 1 día) — no borra nada, las
-- lecturas viejas se quedan para el histórico, solo dejan de contar
-- para el tope una vez pasan las 24h.
create or replace function public.enforce_reading_limit()
 returns trigger
 language plpgsql
 security definer
 set search_path to 'public'
as $function$
declare
  current_count int;
  max_allowed int;
begin
  select count(*) into current_count
  from telemetry
  where device_id = new.device_id
    and recorded_at >= now() - interval '1 day';

  select p.max_readings_per_device into max_allowed
    from plans p join tenants t on t.plan_id = p.id where t.id = new.tenant_id;

  if current_count >= max_allowed then
    raise exception 'Límite de lecturas diarias alcanzado para este dispositivo según tu plan (máx. % por día).', max_allowed;
  end if;

  return new;
end;
$function$;

create trigger before_insert_telemetry_check_limit
  before insert on public.telemetry
  for each row execute function enforce_reading_limit();

-- ---------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------

alter table public.plans enable row level security;
alter table public.tenants enable row level security;
alter table public.profiles enable row level security;
alter table public.devices enable row level security;
alter table public.telemetry enable row level security;

create policy "cualquiera puede ver los planes"
  on public.plans for select
  to public
  using (true);

create policy "usuarios ven su propio tenant"
  on public.tenants for select
  to public
  using (id = get_my_tenant_id());

create policy "usuarios actualizan su propio tenant"
  on public.tenants for update
  to public
  using (id = get_my_tenant_id())
  with check (id = get_my_tenant_id());

create policy "usuarios ven su propio perfil"
  on public.profiles for select
  to public
  using (id = auth.uid());

create policy "usuarios ven dispositivos de su tenant"
  on public.devices for select
  to public
  using (tenant_id = get_my_tenant_id());

create policy "usuarios crean dispositivos en su tenant"
  on public.devices for insert
  to public
  with check (tenant_id = get_my_tenant_id());

create policy "usuarios eliminan dispositivos de su tenant"
  on public.devices for delete
  to public
  using (tenant_id = get_my_tenant_id());

create policy "usuarios ven telemetria de su tenant"
  on public.telemetry for select
  to public
  using (tenant_id = get_my_tenant_id());
