-- =====================================================================
-- Respaldo del esquema de la base de datos — plataforma-iot-tesis
-- =====================================================================
-- Este archivo NO contiene datos (usuarios, dispositivos, telemetría) —
-- solo la estructura: tablas, relaciones, políticas de seguridad (RLS)
-- y las funciones/trigger que provisionan un tenant nuevo al registrarse
-- un usuario.
--
-- Generado a mano a partir de consultas a information_schema / pg_catalog
-- en el SQL Editor de Supabase (no vía `supabase db dump`, que requiere
-- Docker). Refleja el estado del esquema en la fecha de este commit.
--
-- Para reconstruir el proyecto desde cero en un Supabase nuevo:
--   1. Correr este archivo completo en el SQL Editor.
--   2. Configurar Authentication > Providers según corresponda.
--   3. Volver a apuntar HIVEMQ_* / SUPABASE_* en los .env del bridge y
--      del frontend al nuevo proyecto.
-- =====================================================================

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------
-- Tablas
-- ---------------------------------------------------------------------

create table public.tenants (
  id uuid not null default gen_random_uuid(),
  name text not null,
  created_at timestamp with time zone default now(),
  constraint tenants_pkey primary key (id)
);

create table public.profiles (
  id uuid not null,
  tenant_id uuid,
  full_name text,
  role text default 'member',
  created_at timestamp with time zone default now(),
  constraint profiles_pkey primary key (id),
  constraint profiles_id_fkey foreign key (id) references auth.users (id),
  constraint profiles_tenant_id_fkey foreign key (tenant_id) references public.tenants (id)
);

create table public.devices (
  id uuid not null default gen_random_uuid(),
  tenant_id uuid,
  name text not null,
  device_key text not null,
  status text default 'offline',
  created_at timestamp with time zone default now(),
  metric_key text,
  unit text,
  constraint devices_pkey primary key (id),
  constraint devices_tenant_id_fkey foreign key (tenant_id) references public.tenants (id)
);

create table public.telemetry (
  id bigint generated by default as identity,
  tenant_id uuid,
  device_id uuid,
  payload jsonb not null,
  recorded_at timestamp with time zone default now(),
  constraint telemetry_pkey primary key (id),
  constraint telemetry_tenant_id_fkey foreign key (tenant_id) references public.tenants (id),
  constraint telemetry_device_id_fkey foreign key (device_id) references public.devices (id)
);

-- ---------------------------------------------------------------------
-- Funciones
-- ---------------------------------------------------------------------

-- Devuelve el tenant_id del usuario autenticado actual. Se usa dentro
-- de las políticas RLS de abajo para filtrar filas por organización.
create or replace function public.get_my_tenant_id()
 returns uuid
 language sql
 stable security definer
as $function$
  select tenant_id from profiles where id = auth.uid();
$function$;

-- Se ejecuta automáticamente (vía el trigger de más abajo) cada vez que
-- alguien se registra: crea su tenant y su perfil como admin de ese
-- tenant. Es lo que hace que cada usuario nuevo "funde" su propia
-- organización sin lógica de tenant hardcodeada en el código de la app.
create or replace function public.handle_new_user()
 returns trigger
 language plpgsql
 security definer
 set search_path to 'public'
as $function$
declare
  new_tenant_id uuid;
begin
  insert into tenants (name)
  values (coalesce(new.raw_user_meta_data->>'full_name', new.email) || ' - Organización')
  returning id into new_tenant_id;

  insert into profiles (id, tenant_id, full_name, role)
  values (new.id, new_tenant_id, new.raw_user_meta_data->>'full_name', 'admin');

  return new;
end;
$function$;

-- ---------------------------------------------------------------------
-- Trigger (vive en el esquema auth, se define aparte de las funciones)
-- ---------------------------------------------------------------------

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function handle_new_user();

-- ---------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------

alter table public.tenants enable row level security;
alter table public.profiles enable row level security;
alter table public.devices enable row level security;
alter table public.telemetry enable row level security;

create policy "usuarios ven su propio tenant"
  on public.tenants for select
  to public
  using (id = get_my_tenant_id());

create policy "usuarios ven su propio perfil"
  on public.profiles for select
  to public
  using (id = auth.uid());

create policy "usuarios ven dispositivos de su tenant"
  on public.devices for select
  to public
  using (tenant_id = get_my_tenant_id());

create policy "usuarios ven telemetria de su tenant"
  on public.telemetry for select
  to public
  using (tenant_id = get_my_tenant_id());
